apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h906a45ng-nodejs
  janus-idp.io/tekton: h906a45ng-nodejs
  backstage.io/kubernetes-id: h906a45ng-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h906a45ng-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
